apiVersion: v1
kind: Service
metadata:
  name: ghss-otel-collector
spec:
  type: ClusterIP
  ports:
    - name: jaeger
      protocol: TCP
      port: 6831
      targetPort: 6831
  selector:
    app: ghss-otel-collector
