apiVersion: v1
kind: Service
metadata:
  name: ghss-store
spec:
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: ghss-store
