{
 "title": "Builds",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "build",
    "query": "SHOW TAG VALUES WITH KEY = \"name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Attempts",
   "type": "graph",
   "description": "Attempts we took per build. Ideally 1. It's not guaranteed, that a build succeeded after these attempts.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(attempts) FROM build_per_commit WHERE \"name\" =~ /^$build$/ AND $timeFilter GROUP BY time($__interval),\"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Attempts by pipeline",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT mean(\"attempts\") FROM \"build_per_commit\" WHERE \"name\" =~ /^$build$/ AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "attempts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(duration_ms) FROM build WHERE \"name\" =~ /^$build$/ AND $timeFilter GROUP BY time($__interval),\"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success rate by pipeline",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT mean(\"successful\") FROM \"build\" WHERE \"name\" =~ /^$build$/ AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "first_attempt_successful" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duration by pipeline",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "build",
     "query": "SELECT mean(\"duration_ms\") FROM \"build\" WHERE \"name\" =~ /^$build$/ AND $timeFilter GROUP BY time($__interval), \"name\"",
     "select": [
      [
       { "params": [ "first_attempt_successful" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}