apiVersion: v1
kind: ConfigMap
metadata:
  name: ghss-grafana
data:
  grafana.ini: |-
    [server]
    #root_url = https://github-status-stats.kuehle.me/
    #root_url = http://kubernetes.docker.internal/grafana/
    root_url = http://kubernetes.docker.internal/
    #serve_from_sub_path = true
    enable_gzip = true

    [security]
    #cookie_secure = true
    cookie_samesite = strict
    disable_gravatar = true
    x_content_type_options = true
    x_xss_protection = true

    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Viewer

    [auth]
    login_cookie_name = grafana
    login_maximum_inactive_lifetime_days = 1
    login_maximum_lifetime_days = 1
    token_rotation_interval_minutes = 10
    #disable_login_form = true
    disable_signout_menu = true

    [auth.basic]
    #enabled = false

    [auth.proxy]
    enabled = true
    header_name = X-WEBAUTH-USER
    headers = Name:X-WEBAUTH-NAME Email:X-WEBAUTH-EMAIL
    #enable_login_token = true

    [analytics]
    check_for_updates = false

    [explore]
    enabled = false

    [metrics]
    enabled = false

    [snapshots]
    external_enabled = false

    [alerting]
    enabled = false
