apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ghss-importer
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: importer
              image: frigus02/github-status-stats-importer
              env:
                - name: GH_APP_ID
                  value: "50487"
                - name: GH_PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ghss-github
                      key: PRIVATE_KEY
                - name: INFLUXDB_BASE_URL
                  value: http://ghss-influxdb
                - name: INFLUXDB_ADMIN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ghss-influxdb
                      key: admin_username
                - name: INFLUXDB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ghss-influxdb
                      key: admin_password
                - name: INFLUXDB_READ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ghss-influxdb
                      key: read_password
                - name: HONEYCOMB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ghss-honeycomb
                      key: API_KEY
                - name: HONEYCOMB_DATASET
                  valueFrom:
                    secretKeyRef:
                      name: ghss-honeycomb
                      key: DATASET
              resources:
                requests:
                  cpu: 50m
                  memory: 50Mi
                limits:
                  cpu: 50m
                  memory: 50Mi
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
          restartPolicy: OnFailure
