apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ghss-importer
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: importer
              image: frigus02/github-status-stats-importer
              imagePullPolicy: Always
              env:
                - name: RUST_LOG
                  value: info,importer=debug,github_client=debug,grafana_client=debug,influxdb_client=debug
                - name: GH_APP_ID
                  value: "50487"
                - name: GH_PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ghss-github
                      key: PRIVATE_KEY
                - name: INFLUXDB_BASE_URL
                  value: http://ghss-influxdb
                - name: INFLUXDB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ghss-influxdb
                      key: username
                - name: INFLUXDB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ghss-influxdb
                      key: password
                - name: GRAFANA_BASE_URL
                  value: http://ghss-grafana
                - name: GRAFANA_ADMIN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ghss-grafana
                      key: username
                - name: GRAFANA_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ghss-grafana
                      key: password
          restartPolicy: OnFailure
