apiVersion: v1
kind: Service
metadata:
  name: ghss-influxdb
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8086
  selector:
    app: ghss-influxdb
